### ISSUE TITLE
Warning on unmet peer dependency for restify

### ISSUE THREAD

**Issue by jasonfma** [Tabcorp/restify-cors-middleware#36]
restify has released 5.0.0

As part of their migration guide, they suggest to use this library as a replacement for CORS. When I install I get a warning:

```
npm WARN restify-cors-middleware@1.0.0 requires a peer of restify@2.6.x - 4.3.x but none was installed.
```

Any risk on updating the peer dependency? I'm happy to submit a PR.

**Comment by joaoritter** [comment]
Please bump up the dependency to 5!

**Comment by seoker** [comment]
`restify` `6.0.0` has released.
