### ISSUE TITLE
headers not added on get request

### ISSUE THREAD

**Issue by jamesbirtles** [Tabcorp/restify-cors-middleware#58]
Hi,

I'm trying to make an api that is accessible across any domain and this means I need the headers to be added on GET requests. Browsers do not send the Origin header on a GET request and so this doesn't currently seem possible.

Here is my code
```js
    const server = createServer();
    const cors = corsMiddleware({
        origins: ['*'],
        allowHeaders: ['Authorization'],
        exposeHeaders: ['x-jwt'],
    });

    server.pre(cors.preflight);
    server.use(cors.actual);

    // ...
```

**Comment by jurgob** [comment]
+1
