### ISSUE TITLE
Return 200 rather than 204 for non spec complaint libraries

### ISSUE THREAD

**Issue by jacktuck** [Tabcorp/restify-cors-middleware#61]
Since upgrading to restify and using restify-cors-middleware we're now getting 204 for OPTIONS requests - which is fine as per the spec. But since we're now getting 204s rather than 200s when we were using restify's built in plugin for cors one of our ios libraries have been failing.

Since the spec allows 200 or 204 can we switch back over to 200 to keep in line with the old restify way and return content length 0 with the 200?

> 
> A 200 response SHOULD...
> 
> ...
> 
> If no response body is included, the response MUST include a Content-Length field with a field-value of "0".

If this is acceptable i'm happy to PR.

**Comment by jacktuck** [comment]
Sorry for the noise: turned out i was off base here it was a different issue with restify changing their accept parser.

**Comment by proxy-hatch** [comment]
hey @jacktuck  what was the issue in your case? I'm seeing 204 as response as well and I'd like to return 200 instead.

I can see in src code it does seem to return 204 
https://github.com/Tabcorp/restify-cors-middleware/blob/master/src/preflight.js#L41
