### ISSUE TITLE
Causing a warning with Restify 7

### ISSUE THREAD

**Issue by goyney** [Tabcorp/restify-cors-middleware#63]
> restify-cors-middleware@1.1.0" has incorrect peer dependency "restify@2.6.x - 6.x.x".

The module seems to work correctly, however it produces this warning. If this module is certified to work with Restify 7, could you update the peer dependencies to include 7 to remove the warnings?

**Comment by frbuceta** [comment]
just need to accept the pull request and ready #64

**Comment by deancouch** [comment]
Published https://www.npmjs.com/package/restify-cors-middleware/v/1.1.1
