### ISSUE TITLE
patch request fails

### ISSUE THREAD

**Issue by pshergie** [Tabcorp/restify-cors-middleware#72]
Access to fetch at 'http://127.0.0.1:8888/xxx?yyy=zzz' from origin 'http://localhost:3333' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I'm using fetch API. Also tried to use `new XMLHttpRequest();` but it also failed (just another error).

Could anybody say what am I doing wrong?

I enabled all requests in node.js:
```
const cors = corsMiddleware({
  preflightMaxAge: 5, //Optional
  origins: ['*']
})

server.pre(cors.preflight);
server.use(cors.actual);
```

**Comment by Karanval** [comment]
how did u solve this? I have a similar problem, but with post method, even though I specify:
allowHeaders: ['*', 'Authorization']

thanks for any input.

**Comment by pshergie** [comment]
> how did u solve this? I have a similar problem, but with post method, even though I specify:
> allowHeaders: ['*', 'Authorization']
> 
> thanks for any input.

My problem was that I was doing request at wrong url. I hadn't any handler for wrong paths, so I had I cors error.
